import os
import buildConfig
#get options and set default value
debug = ARGUMENTS.get('debug', 1)

class LayerBuildConfig(buildConfig.buildConfigForC):
    def __init__(self, isDebug):
        super().__init__(isDebug)
        if(self.isDebug==1):
            self.targetName="layerLibDebug"
        else:
            self.targetName="layerLibRelease"

config = LayerBuildConfig(debug)

LayerSrcs = Glob("./*.c")

layerEnv = Environment(CC=config.CC, CCFLAGS=config.CCFLAGS, CPPPATH=config.incDirs,
    CPPDEFINES=config.preDifines,ENV = {'PATH' : os.environ['PATH']})

layerEnv.SharedLibrary(target = config.targetName, source =LayerSrcs,LIBS=config.linkOpt, LIBPATH=config.linkDir)