import os
import buildConfig
#get options and set default value
debug = ARGUMENTS.get('debug', 1)
print(debug)
config = buildConfig.MlpBuildConfig(debug)

print(config.CCFLAGS)

mlpLibEnv = Environment(CXX=config.CXX,CC=config.CC, CCFLAGS=config.CCFLAGS, CPPPATH=config.incDirs,
    CPPDEFINES=config.preDifines,ENV = {'PATH' : os.environ['PATH']})
mlpSource = Glob("./*.cpp")

mlpLibEnv.SharedLibrary(target = config.targetName, source = mlpSource,LIBS=config.linkOpt, LIBPATH=config.linkDir)